<?php

return [
    'fields' => [
        'name' => [
            'header' => 'Наименование',
            'type' => 'string',
            'required' => true,
            'importable' => false,
            'export_default' => true,
        ],
        'new_name' => [
            'header' => 'Новое наименование',
            'type' => 'string',
            'required' => false,
            'importable' => true,
            'export_default' => true,
            'virtual' => true,
        ],
        'sku' => [
            'header' => 'Артикул',
            'type' => 'string',
            'importable' => true,
            'export_default' => true,
        ],
        'brand' => [
            'header' => 'Бренд',
            'type' => 'string',
            'importable' => true,
            'export_default' => true,
        ],
        'country' => [
            'header' => 'Страна',
            'type' => 'string',
            'importable' => true,
            'export_default' => true,
        ],
        'price_amount' => [
            'header' => 'Цена',
            'type' => 'integer',
            'importable' => true,
            'export_default' => true,
        ],
        'discount_price' => [
            'header' => 'Цена со скидкой',
            'type' => 'integer',
            'importable' => true,
            'export_default' => true,
        ],
        'qty' => [
            'header' => 'Кол-во',
            'type' => 'integer',
            'importable' => true,
            'export_default' => true,
        ],
        'currency' => [
            'header' => 'Валюта',
            'type' => 'string',
            'importable' => true,
            'export_default' => false,
        ],
        'in_stock' => [
            'header' => 'В наличии',
            'type' => 'boolean',
            'importable' => true,
            'export_default' => true,
        ],
        'is_active' => [
            'header' => 'Показывать на сайте',
            'type' => 'boolean',
            'importable' => true,
            'export_default' => true,
        ],
        'is_in_yml_feed' => [
            'header' => 'Выгружать в фид YML',
            'type' => 'boolean',
            'importable' => true,
            'export_default' => true,
        ],
        'with_dns' => [
            'header' => 'С НДС',
            'type' => 'boolean',
            'importable' => true,
            'export_default' => true,
        ],
        'warranty' => [
            'header' => 'Гарантия',
            'type' => 'string',
            'importable' => true,
            'export_default' => true,
        ],
        'title' => [
            'header' => 'Заголовок товара',
            'type' => 'string',
            'importable' => true,
            'export_default' => false,
        ],
        'meta_title' => [
            'header' => 'Meta Title',
            'type' => 'string',
            'importable' => true,
            'export_default' => false,
        ],
        'meta_description' => [
            'header' => 'Meta Description',
            'type' => 'text',
            'importable' => true,
            'export_default' => false,
        ],
        'short' => [
            'header' => 'Краткое описание',
            'type' => 'text',
            'importable' => true,
            'export_default' => false,
        ],
        'description' => [
            'header' => 'Описание',
            'type' => 'longtext',
            'importable' => true,
            'export_default' => false,
        ],
        'extra_description' => [
            'header' => 'Доп. описание',
            'type' => 'text',
            'importable' => true,
            'export_default' => false,
        ],
        'promo_info' => [
            'header' => 'Промо',
            'type' => 'string',
            'importable' => true,
            'export_default' => false,
        ],
        'image' => [
            'header' => 'Изображение',
            'type' => 'string',
            'importable' => false,
            'export_default' => false,
        ],
        'thumb' => [
            'header' => 'Превью',
            'type' => 'string',
            'importable' => false,
            'export_default' => false,
        ],
        'gallery' => [
            'header' => 'Галерея',
            'type' => 'longtext',
            'importable' => false,
            'export_default' => false,
        ],
        'updated_at' => [
            'header' => 'Изменено',
            'type' => 'datetime',
            'required' => true,
            'importable' => false,
            'export_default' => true,
        ],
    ],

    'forced_columns' => ['name', 'updated_at'],

    'default_export' => [
        'name',
        'new_name',
        'sku',
        'brand',
        'country',
        'price_amount',
        'discount_price',
        'qty',
        'warranty',
        'in_stock',
        'is_active',
        'is_in_yml_feed',
        'with_dns',
        'updated_at',
    ],

    'staging_category_slug' => 'staging',
];
