<?php

return [
    'routes' => [
        'filament.admin.resources.attributes.index' => 'https://help.stankoman.ru/attributes/',
        'filament.admin.resources.attributes.create' => 'https://help.stankoman.ru/attributes/create/',
        'filament.admin.resources.attributes.edit' => 'https://help.stankoman.ru/attributes/edit/',
        'filament.admin.pages.catalog-supplier-import' => 'https://help.stankoman.ru/import/supplier-import/',
        'filament.admin.resources.categories.index' => 'https://help.stankoman.ru/categories/',
        'filament.admin.resources.categories.create' => 'https://help.stankoman.ru/categories/create/',
        'filament.admin.resources.categories.edit' => 'https://help.stankoman.ru/categories/edit/',
        'filament.admin.pages.category-filters-import-export' => 'https://help.stankoman.ru/import/category-filters-import-export/',
        'filament.admin.pages.category-tree' => 'https://help.stankoman.ru/categories/tree/',
        'filament.admin.pages.home' => 'https://help.stankoman.ru/home/',
        'filament.admin.pages.import-export-help' => 'https://help.stankoman.ru/import/help/',
        'filament.admin.resources.import-runs.index' => 'https://help.stankoman.ru/import/history/',
        'filament.admin.resources.import-runs.view' => 'https://help.stankoman.ru/import/history/view/',
        'filament.admin.resources.menus.index' => 'https://help.stankoman.ru/menus/',
        'filament.admin.resources.menus.create' => 'https://help.stankoman.ru/menus/create/',
        'filament.admin.resources.menus.builder' => 'https://help.stankoman.ru/menus/builder/',
        'filament.admin.resources.menus.edit' => 'https://help.stankoman.ru/menus/edit/',
        'filament.admin.resources.orders.index' => 'https://help.stankoman.ru/orders/',
        'filament.admin.resources.orders.create' => 'https://help.stankoman.ru/orders/create/',
        'filament.admin.resources.orders.view' => 'https://help.stankoman.ru/orders/view/',
        'filament.admin.resources.orders.edit' => 'https://help.stankoman.ru/orders/edit/',
        'filament.admin.resources.pages.index' => 'https://help.stankoman.ru/pages/',
        'filament.admin.resources.pages.create' => 'https://help.stankoman.ru/pages/create/',
        'filament.admin.resources.pages.edit' => 'https://help.stankoman.ru/pages/edit/',
        'filament.admin.pages.product-import-export' => 'https://help.stankoman.ru/import/excel-import/',
        'filament.admin.resources.products.index' => 'https://help.stankoman.ru/products/',
        'filament.admin.resources.products.create' => 'https://help.stankoman.ru/products/create/',
        'filament.admin.resources.products.edit' => 'https://help.stankoman.ru/products/edit/',
        'filament.admin.resources.settings.index' => 'https://help.stankoman.ru/settings/',
        'filament.admin.resources.settings.create' => 'https://help.stankoman.ru/settings/create/',
        'filament.admin.resources.settings.edit' => 'https://help.stankoman.ru/settings/edit/',
        'filament.admin.resources.sliders.index' => 'https://help.stankoman.ru/sliders/',
        'filament.admin.resources.sliders.create' => 'https://help.stankoman.ru/sliders/create/',
        'filament.admin.resources.sliders.edit' => 'https://help.stankoman.ru/sliders/edit/',
        'filament.admin.pages.supplier-import' => 'https://help.stankoman.ru/import/yandex-feed-import/',
        'filament.admin.resources.units.index' => 'https://help.stankoman.ru/units/',
        'filament.admin.resources.units.create' => 'https://help.stankoman.ru/units/create/',
        'filament.admin.resources.units.edit' => 'https://help.stankoman.ru/units/edit/',
        'filament.admin.resources.users.index' => 'https://help.stankoman.ru/users/',
        'filament.admin.resources.users.create' => 'https://help.stankoman.ru/users/create/',
        'filament.admin.resources.users.edit' => 'https://help.stankoman.ru/users/edit/',
        'filament.admin.pages.yandex-market-feed-deactivate' => 'https://help.stankoman.ru/import/yandex-feed-deactivate/',
        'filament.admin.pages.yandex-market-feed-import' => 'https://help.stankoman.ru/import/yandex-feed-import/',
    ],
];
